#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
  use FindBin '$RealScript';
  use File::Basename;
  $ENV{BASENAME} = basename( $RealScript );
}

use lib "$ENV{BASENAME}/lib";

use Log::Any::Adapter;

#use ManageMod::GetData;
use ManageMod::GetMod;

#Log::Any::Adapter->set( 'File', "$HOME/.local/$ENV{BASENAME}" );
Log::Any::Adapter->set( 'File', "$ENV{BASENAME}.log" );

my $data = get_mod('jei', '1.12.2', 'release,beta');

use JSON;
my $json = JSON->new;
print $json->pretty->encode($data);
