#!/usr/bin/env perl

## no critic

use strict;
use warnings;

BEGIN {
  use FindBin '$RealScript';
  use File::Basename;

  $ENV{MANAGE_MOD_VERSION}     = '0.01';
  $ENV{MANAGE_MOD_BASENAME}    = basename( $RealScript );
  $ENV{MANAGE_MOD_CACHE_DIR} //= "$ENV{HOME}/.cache/$ENV{MANAGE_MOD_BASENAME}";
  $ENV{MANAGE_MOD_AGENT}     //= "HarleyPig's Mod Manager/$ENV{MANAGE_MOD_VERSION}";

  [[ -d $ENV{MANAGE_MOD_CACHE_DIR} ]]
    or mkdir $ENV{MANAGE_MOD_CACHE_DIR}
      or die "Unable to create cache dir.";
}

use lib "$ENV{MANAGE_MOD_BASENAME}/lib";

use Log::Any::Adapter;
use ManageMod::CurseForge::GetModInfo;
use YAML::Syck;

#Log::Any::Adapter->set( 'File', "$HOME/.local/$ENV{BASENAME}" );
Log::Any::Adapter->set( 'File', "$ENV{MANAGE_MOD_BASENAME}.log", log_level => 'debug' );

# !!! Need to account for projects not in minecraft.curseforge.com but are in
# curseforge.com/minecraft.

# Worlds: skyblock-3
# Modpacks: stoneblock
# Customization: astral-lucky-blocks
# Addons: minecraft-font
# Mods: jei
# Texture Packs: faithful-x32

my $mod = 'orelib';
my $ver = '1.12.2';
my $channels = 'release,beta';

my $data = get_mod_info($mod, $ver, $channels);

$YAML::Syck::SortKeys++;
DumpFile("$mod.yml", $data);

# What mod?
# What version of minecraft?
# What channels?
# Get mod info.
# Does jar already exist?
#  Download jar
# Does jar match md5sum?
#
